### ISSUE TITLE
Create barebones Chrome Extension w/ static content

### ISSUE THREAD

**Issue by warut-vijit** [kenwuuu/YouTubeSearchBySubscriptions#3]
If your team would like to implement the front-end as a Chrome Extension, build a barebones one with static content using instructions from [this](https://developer.chrome.com/extensions/getstarted) link and placeholder content.

**Comment by warut-vijit** [comment]
@kevinjw2 assigning to you, pm on Slack or comment here if you encounter any issues with this.

**Comment by kevinjw2** [comment]
Gotcha
